# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Notflix' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   platform :ios, '16.0'
   pod 'shared', :path => '../shared'
 =begin   pod 'SDWebImageSwiftUI'
   pod 'KMPNativeCoroutinesAsync','0.12.2' =end

 end

 post_install do |installer|
   installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
     end
   end

end
