object BuildPlugins {
    const val kotlinAndroid = "kotlin-android"
    const val androidApplication = "com.android.application"
    const val androidLibrary = "com.android.library"
    const val kotlinKapt = "kotlin-kapt"
    const val kotlin = "kotlin"
    const val java = "java-library"
    const val dynamicFeature = "com.android.dynamic-feature"
    const val realmAndroid = "realm-android"
    const val googleServices = "com.google.gms.google-services"
    const val firebaseCrashlytics = "com.google.firebase.crashlytics"
    const val kotlinSafeArgs = "androidx.navigation.safeargs.kotlin"
    const val ktlintPlugin = "org.jlleitschuh.gradle.ktlint"
    const val detektPlugin = "io.gitlab.arturbosch.detekt"
    const val spotlessPlugin = "com.diffplug.spotless"
    const val dokkaPlugin = "org.jetbrains.dokka"
    const val jacocoAndroid = "com.hiya.jacoco-android"
    const val gradleVersions = "com.github.ben-manes.versions"
    const val firebasePerformance = "com.google.firebase.firebase-perf"
    const val kotlinParcelize = "kotlin-parcelize"

    const val multiplatform="multiplatform"
    const val kotlinXSerialization="plugin.serialization"
    const val sqlDelight="com.squareup.sqldelight"
}
