target 'Notflix' do
  use_frameworks!
   platform :ios, '16.0'
   pod 'shared', :path => '../shared'
   pod 'KMPNativeCoroutinesAsync','0.12.2'
 end

 post_install do |installer|
   installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
     end
   end

end
