name: Build & Deploy Android Debug
on:
  workflow_dispatch:
    inputs:
      versionCode:
        description: Version Code (eg. 123)
        required: true
      versionName:
        description: Version Name (eg 1.2.3)
        required: true

env:
  VERSION_CODE: ${{ github.event.inputs.versionCode }}
  VERSION_NAME: ${{ github.event.inputs.versionName }}

jobs:

  build:
    name: 🔨 Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew :shared:clean :shared:build --stacktrace

      - name: Get local.properties from secrets
        run: echo "${{secrets.LOCAL_PROPERTIES }}" > $GITHUB_WORKSPACE/local.properties

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: production
          file: appAndroid/build/outputs/apk/debug/appAndroid-debug.apk
